// AUTO-GENERATED BY @sidebase/nuxt-auth
declare module '#auth' {
  const { getServerSession, getToken, NuxtAuthHandler }: typeof import('C:/Users/HP/Desktop/Senior Project/BizFind/frontend/node_modules/@sidebase/nuxt-auth/dist/runtime/server/services')
}
